# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreDataN-N' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreDataN-N
pod 'FolioReaderKit'

end
