# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FashionApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FashionApp
	pod 'Firebase/Auth'
	pod 'Firebase/Analytics'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'Alamofire'
	pod 'Kingfisher'
#    	pod 'FBSDKLoginKit'
	pod 'GoogleSignIn'
	pod 'ObjectMapper'
	pod 'DropDown'
	pod 'TTGTagCollectionView'
end
