//
//  HomeRouter.swift
//  DemoVIPER
//
//  Created Apple on 7/28/20.
//  Copyright © 2020 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeRouter: HomeWireframeProtocol {
  
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HomeViewController(nibName: nil, bundle: nil)
        let interactor = HomeInteractor()
        let router = HomeRouter()
        let presenter = HomePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func showDetailVC() {
        let detailVC = DetailVC()
        detailVC.textFromUser = "Tao lay may"
        viewController?.navigationController?.pushViewController(detailVC, animated: true)
    }
}
