//
//  HomePresenter.swift
//  DemoVIPER
//
//  Created Apple on 7/28/20.
//  Copyright © 2020 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePresenter {
    
    
    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorInputProtocol?
    private let router: HomeWireframeProtocol
    
    
    init(interface: HomeViewProtocol, interactor: HomeInteractorInputProtocol?, router: HomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension HomePresenter: HomePresenterProtocol {
    func startGetUser() {
        interactor?.getUser()
    }
    
    func showDetail() {
        router.showDetailVC()
    }

}

extension HomePresenter: HomeInteractorOutputProtocol {
    func getUserSuccess(user: [User]) {
        view?.showUser(user: user)
    }
    
    func getUserFail() {
        
    }
    
    
}


