//
//  HomeProtocols.swift
//  DemoVIPER
//
//  Created Apple on 7/28/20.
//  Copyright © 2020 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: class {
    func showDetailVC()

}
//MARK: Presenter -
protocol HomePresenterProtocol: class {
    
    var interactor: HomeInteractorInputProtocol? { get set }
    
    func startGetUser()
    
    //navigation
    func showDetail()
    
}

//MARK: Interactor -

// delegate truyen du lieu lai cho presenter
protocol HomeInteractorOutputProtocol: class {
    
    func getUserSuccess(user: [User])
    func getUserFail()

    /* Interactor -> Presenter */
}

protocol HomeInteractorInputProtocol: class {

    var presenter: HomeInteractorOutputProtocol?  { get set }
    
    func getUser()

    /* Presenter -> Interactor */
}

//MARK: View -
protocol HomeViewProtocol: class {

    var presenter: HomePresenterProtocol?  { get set }
    
    func showUser(user: [User])

    /* Presenter -> ViewController */
}
