//
//  HomeViewController.swift
//  DemoVIPER
//
//  Created Apple on 7/28/20.
//  Copyright © 2020 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeViewController: UIViewController, HomeViewProtocol {

	var presenter: HomePresenterProtocol?
    
	override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.startGetUser()
        
    }
    @IBAction func onTapBtn(_ sender: UIButton) {
        presenter?.showDetail()
    }
    
    func showUser(user: [User]) {
        print(user)
    }

}
