//
//  HomeInteractor.swift
//  DemoVIPER
//
//  Created Apple on 7/28/20.
//  Copyright © 2020 vinova. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeInteractor: HomeInteractorInputProtocol {

    weak var presenter: HomeInteractorOutputProtocol?
    
    func getUser() {
        let url = URL(string: "https://jsonplaceholder.typicode.com/users")
        let task = URLSession.shared.dataTask(with: url!) { (data, _, err) in
            do {
                guard let data = data else {return}
                
                
                let json = try JSONDecoder().decode([User].self, from: data)
                
            
                DispatchQueue.main.async {
                    self.presenter?.getUserSuccess(user: json)
                }

            } catch {
                print(err?.localizedDescription)
            }
        }

        task.resume()
    }
}


