# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoTodoWithCloudFirestore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoTodoWithCloudFirestore
pod 'SnapKit', '~> 5.0.0'
pod 'Firebase/Firestore'
pod 'Firebase/Analytics'

end
