# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProfileReSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProfileReSwift
pod 'ReSwift'
pod 'Alamofire'
pod "PromiseKit"

end
